CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  balance REAL DEFAULT 1000,
  total_bet REAL DEFAULT 0,
  total_wins REAL DEFAULT 0,
  total_losses REAL DEFAULT 0,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);